name: Collect GitHub Traffic

on:
  workflow_dispatch:
  schedule:
    - cron: "22 1 * * *"   # daily at 01:22 UTC

permissions:
  contents: write          # needed for commits with GITHUB_TOKEN

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set owner/repo
        run: |
          echo "OWNER=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Fetch last 14 days of views (Traffic API via classic PAT)
        env:
          TRAFFIC_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
        run: |
          if [ -z "$TRAFFIC_TOKEN" ]; then
            echo "Missing secret GH_TRAFFIC_TOKEN"; exit 1
          fi
          mkdir -p data
          STATUS=$(curl -sS -w "%{http_code}" -o data/views.json \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TRAFFIC_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${OWNER}/${REPO}/traffic/views?per=day")

          echo "HTTP_STATUS=$STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "API call failed with status $STATUS"
            cat data/views.json
            exit 1
          fi

      - name: Convert to CSV (date,visitors,uniques)
        run: |
          # Validate JSON
          jq -e . >/dev/null 2>&1 < data/views.json || { echo "Invalid JSON"; cat data/views.json; exit 1; }

          # Build CSV; tolerate empty/missing views
          if [ "$(jq 'has(\"views\") and (.views|type==\"array\")' data/views.json)" != "true" ]; then
            echo "date,visitors,uniques" > data/visitors.latest.csv
          else
            jq -r '
              ["date","visitors","uniques"],
              (.views[]? | [(.timestamp[0:10]), (.count|tostring), (.uniques|tostring)])
              | @csv
            ' data/views.json > data/visitors.latest.csv
          fi

      - name: Merge with existing history
        run: |
          # Ensure header exists
          if [ ! -s data/visitors.latest.csv ]; then
            echo "date,visitors,uniques" > data/visitors.latest.csv
          fi

          if [ -f data/visitors.csv ]; then
            # Merge by date; latest snapshot wins; keep sorted
            (head -n1 data/visitors.latest.csv
             tail -n +2 data/visitors.csv
             tail -n +2 data/visitors.latest.csv) \
            | awk -F, 'NR==1{print;next} NR>1{a[$1]=$0} END{for (d in a) print a[d]}' \
            | sort -t, -k1,1 > data/visitors.merged.csv
            mv data/visitors.merged.csv data/visitors.csv
          else
            mv data/visitors.latest.csv data/visitors.csv
          fi

      - name: Commit updated CSV (using GITHUB_TOKEN)
        run: |
          if git diff --quiet --exit-code; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/visitors.csv
            git commit -m "chore: update visitors.csv from Traffic API"
            git push
          fi
